[package]
name = "polkadot-statement-table"
version = "0.8.24"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
codec = { package = "parity-scale-codec", version = "1.3.4", default-features = false, features = ["derive"] }
sp-core = { git = "https://github.com/tomaka/polkadot", branch = "no-longer-open-substream" }
primitives = { package = "polkadot-primitives", path = "../primitives" }
