[package]
name = "polkadot-node-core-runtime-api"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
futures = "0.3.5"
sp-api = { git = "https://github.com/tomaka/polkadot", branch = "no-longer-open-substream" }
sp-blockchain = { git = "https://github.com/tomaka/polkadot", branch = "no-longer-open-substream" }

polkadot-primitives = { path = "../../../primitives" }
polkadot-node-primitives = { path = "../../primitives" }
polkadot-subsystem = { package = "polkadot-node-subsystem", path = "../../subsystem" }

[dev-dependencies]
sp-core = { git = "https://github.com/tomaka/polkadot", branch = "no-longer-open-substream" }
futures = { version = "0.3.5", features = ["thread-pool"] }
polkadot-node-subsystem-test-helpers = { path = "../../subsystem-test-helpers" }
